### ISSUE TITLE
Start Activity

### ISSUE THREAD

**Issue by ghost1372** [googlesamples/android-topeka#37]
hi,
first,tnx for new version(Support pre-lolipop)
second,how i can start blank activity(for example about activity) when user click one of the categories?

**Comment by keyboardsurfer** [comment]
From what I understand this question is not targeted at Topeka directly.
If that is the case, please take a look at [Intents and Intent Filters](https://developer.android.com/guide/components/intents-filters.html) within Android's developer documentation.

**Comment by ghost1372** [comment]
i know how start Activity but i dont know where i must write this code.
for example i want add new categories (About us) when user click on,insted of show quiz i want show another activity.and user click other categories quiz show.

**Comment by keyboardsurfer** [comment]
The `CategorySelectionActivity` holds an `Adapter` which holds the displayed categories.
Currently only an instance of `QuizActivity` will be started due to the implementation of an `OnItemClickListener` within `CategoryFragment`. So starting a new Activity would go in the `OnItemClickListener` implementation.

**Comment by ghost1372** [comment]
tnx bro you again save my day.D:
its work...
