### ISSUE TITLE
AnimationAwareTestRule not working

### ISSUE THREAD

**Issue by cxzhang2** [googlesamples/android-topeka#77]
transitionAnimationScale, windowAnimationScale, animatorDuration scale are always 0, regardless of what the actual settings are.

Tested on real device on M (5x), emulator on L + M

p.s. huge fan of your twitter table flipping

edit 2: found the source of the problem:  if the animation settings have never been touched, Settings.Global.getFloat(resolver, setting) will trigger SettingNotFoundException.  The rule works fine after any of the animation settings are changed at least once. Any solution to this?

**Comment by keyboardsurfer** [comment]
Thanks for the report.
The way this was implemented in the test rule is to catch the exception, log the error and return 0.
So the implementation is working as intended.
I'll have to take a closer look into this.

**Comment by ardock** [comment]
Thanks @cxzhang2  for report this :+1: 

@keyboardsurfer Thanks for create this test rule, I saw you [deleted it](https://github.com/googlesamples/android-topeka/commit/1b0c461e66e5a49fc8dca2ff91f27631bfa95a09), it was useful to avoid reflection.

I disagree, if we catch the exception, the proper default value to be used  is enabled:

        /**
         * Convenience function for retrieving a single secure settings value
         * as a float...
         * This version does not take a default value.  If the setting has not
         * been set, or ...,
         * it throws {@link SettingNotFoundException}.
         *
         * ...
         *
         * @throws SettingNotFoundException Thrown if a setting by the given
         * name can't be found or ...
         *
         * @return The setting's current value.
         */
        public static float getFloat(ContentResolver cr, String name)
                throws SettingNotFoundException {
            String v = getString(cr, name);
            if (v == null) {
                throw new SettingNotFoundException(name);
            }
           ...
        }

The rule tried to detect this fact and wrongly ignored the most common case in CI builds:

```
/**
 * A test rule that will fail a test if animations or transitions are enabled on a device.
 */
public class AnimationAwareTestRule implements TestRule {
```

Thanks, now animations are correctly disabled for API level 21 and I'm going to fix another issue for API level 22 this week. I would appreciate any aid or advice for API level 23 or a confirmation that this is not possible:

```
:app:grantSetAnimationScalePermission
Operation not allowed: java.lang.SecurityException: Permission android.permission.SET_ANIMATION_SCALE is not a changeable permission type
```

**Comment by JoseAlcerreca** [comment]
ardock can you please add more details? Are you doing this?
http://stackoverflow.com/questions/29908110/how-to-disable-animations-in-code-when-running-espresso-tests

**Comment by ardock** [comment]
@JoseAlcerreca Yes see my undeleted response [here](http://stackoverflow.com/questions/33929937/android-marshmallow-test-permissions-with-espresso?noredirect=1&lq=1) just below yours, or the last post [here](https://github.com/ardock/android-topeka/issues/1).

I suppose that using uiautomator also fails because is considered a dangerous permission, code 50, I checked the changes for M months ago, I don't remember now... and I think it's not possible disable animations...

I'm going to try using your response to be sure.

**Comment by ardock** [comment]
@JoseAlcerreca About API 22, there is an ANR "System process isn't responding overlapping the app" so Espresso tests fail. I have logs but I'm not sure which app it's crashing, affects each API 22 CI build...

What do you recommend to dismiss it? Is it possible using UI Automatr like [this](http://stackoverflow.com/questions/15010400/android-emulator-adb-command-to-clear-unforunately-myapp-has-stopped-running)? It's not an app dialog...

I'm going to try [this] because the dialog is under the lock and this shows your app over the lock...

```
package com.mypackage.espressoTest;

import android.view.WindowManager;
import org.junit.Before;
import org.junit.Rule;
import org.junit.runner.RunWith;

import android.support.test.rule.ActivityTestRule;
import android.support.test.runner.AndroidJUnit4;

@RunWith(AndroidJUnit4.class)
class TestClass {
    @Rule
    public ActivityTestRule<MainActivity> mActivityRule = new ActivityTestRule<>(
            MainActivity.class);

    @Before
    public void setUp() {
        MainActivity activity = mActivityRule.getActivity();
        Runnable wakeUpDevice = new Runnable() {
            public void run() {
                activity.getWindow().addFlags(WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON |
                    WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED |
                    WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
            }
        };
        activity.runOnUiThread(wakeUpDevice);
    }
}
```

**Comment by ardock** [comment]
@JoseAlcerreca It works on M devices but not on M emulators due to [this](https://travis-ci.org/ardock/android-topeka/jobs/153158643#L1858):

```
:app:installDebug
Installing APK 'app-debug.apk' on 'test(AVD) - 6.0' for app:debug
Installed on 1 device.
:app:grantSetAnimationScalePermission
Operation not allowed: java.lang.SecurityException: Permission android.permission.SET_ANIMATION_SCALE is not a changeable permission type
:app:connectedDebugAndroidTest
```

I found this [fix](https://android.googlesource.com/platform/frameworks/base/+/9f5b0a2%5E!/).
There was a [bug](https://code.google.com/p/android-developer-preview/issues/detail?id=3229) on M preview.

```
-        if (!bp.isRuntime()) {
+        if (!bp.isRuntime() && !bp.isDevelopment()) {
             throw new SecurityException("Permission " + bp.name
                     + " is not a changeable permission type");
```

From [here](https://github.com/MindMac/Android-PermissionsLevelDescMap/blob/master/permissions.py) or [here](https://github.com/android/platform_frameworks_base/blob/master/core/res/AndroidManifest.xml), I understand this is a development permission:
`"android.permission.SET_ANIMATION_SCALE" : ["signature|system|development", "Modify the global animation scaling factor. Not for use by third-party applications."], `

I'll try to update tools...

**Comment by keyboardsurfer** [comment]
This code is no longer in use and the issue has been stale for almost a year. Considering obsolete.
